### ISSUE TITLE
QSTile on userspace backend doesn't toggle tunnel

### ISSUE THREAD

**Issue by anirudhgupta109** [MSF-Jarvis/wireguard-kt#91] opened 2018-12-08 09:04 UTC
Android toast with with following message comes up
`Error toggling Wireguard tunnel: Unable to create tun device`

A log of the issue captured by the inbuilt logger: https://del.dog/yodirusuno.pl
Device: OnePlus 6
Android Version: Android P (9.0)
Kernel Version: 4.9.141
Does kernel have Wireguard support? : No

**Comment by MSF-Jarvis** [comment] 2018-12-14 08:44
Can you reproduce this on the official client? I don't have a reliable way to reproduce this on my devices and I don't know if this is even something that I can fix.

**Comment by anirudhgupta109** [comment] 2018-12-17 16:21
> Can you reproduce this on the official client? I don't have a reliable way to reproduce this on my devices and I don't know if this is even something that I can fix.

works perfectly on the official client on Go Userbackend

**Comment by MSF-Jarvis** [comment] 2018-12-17 18:16
> > Can you reproduce this on the official client? I don't have a reliable way to reproduce this on my devices and I don't know if this is even something that I can fix.
> 
> works perfectly on the official client on Go Userbackend

The issue seems to happen only on a stale tile/tunnel, try idling the app for a day and try again. I want to be sure before I start digging because I have a huge rewrite to port from upstream soon-ish so I don't want any lingering issues before I start.

**Comment by MSF-Jarvis** [comment] 2018-12-18 08:48
Fixed with 32d0c90

**Closed by MSF-Jarvis** 2018-12-18 08:48 UTC
Labels: bug
